name: Release and Pip Package Action
'on':
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - master
      - main
jobs:
  release:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Create Semantic Release
        uses: matteo4diani/poetry-semantic-release@v0
        id: create-release
        with:
          github-token: '${{ secrets.GITHUB_TOKEN }}'
          pypi-token: '${{ secrets.PYPI_TOKEN }}'
          python-version: 3.12.5
    outputs:
      released: '${{ steps.create-release.outputs.released }}'
      tag: '${{ steps.create-release.outputs.tag }}'
      version: '${{ steps.create-release.outputs.version }}'
